name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image 
      uses: docker/build-push-action@v6
      with:
        context: ./.devcontainer
        file: ./.devcontainer/Dockerfile
        platforms: linux/amd64
        # cache-from: type=local,src=/tmp/.devcontainer-cache
        # cache-to: type=local,dest=/tmp/.devcontainer-cache

      # run: docker buildx build --push --platform linux/amd64 -t compiler-image -f ./.devcontainer/Dockerfile ./.devcontainer \
      #   --cache-from=type=local,src=/tmp/.devcontainer-cache \
      #   --cache-to=type=local,dest=/tmp/.devcontainer-cache

