name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker image 
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/${{ github.repository_owner }}/baby:latest
        context: ./.devcontainer
        file: ./.devcontainer/Dockerfile
        platforms: linux/amd64
        push: true

    - name: Test docker image
      run: docker run ghcr.io/${{ github.repository_owner }}/baby echo "Hello, World again!"